changes to match new preseed_fetch approach
git-svn-id: http://svn.hands.com/d-i@152 33d97d02-e2f8-0310-af11-9b3162d49f83

diff --git a/trunk/classes/early_script b/trunk/classes/early_script
--- a/trunk/classes/early_script
+++ b/trunk/classes/early_script
@@ -4,7 +4,7 @@
 # distributed under the terms of the GNU GPL version 2 or (at your option) any later version
 # see the file "COPYING" for details
 
-#set -e
+set -e
 
 MYNAME="classes/early_script"
 
@@ -13,13 +13,14 @@ MYNAME="classes/early_script"
 
 log "debug: Running..."
 
-set -x
+db_register preseed/meta/text hands-off/title
+db_register preseed/meta/text hands-off/item
 
-db_subst ai/meta/text1 TEXT "Preseed early_script(s)"
-db_progress START 0 $({ echo myself; classes; } | wc -w) ai/meta/text1
+db_subst hands-off/title DESC "Preseed early_script(s)"
+db_progress START 0 $({ echo myself; classes; } | wc -w) hands-off/title
 
-db_subst ai/meta/text2 TEXT "Running top level script"
-db_progress INFO ai/meta/text2
+db_subst hands-off/item DESC "Running top level script"
+db_progress INFO hands-off/item
 
 # script to restart the install -- handy for testing
 {
@@ -30,7 +31,7 @@ chmod +x /usr/bin/zapme
 
 # package to allow packages to be excluded from the base install
 BSW_VER=0.2
-ai_fetch_file /udebs/bootstrapwrap_${BSW_VER}_all.udeb /tmp/bootstrapwrap_${BSW_VER}_all.udeb &&
+preseed_fetch /udebs/bootstrapwrap_${BSW_VER}_all.udeb /tmp/bootstrapwrap_${BSW_VER}_all.udeb &&
   udpkg -i /tmp/bootstrapwrap_${BSW_VER}_all.udeb &&
   rm /tmp/bootstrapwrap_${BSW_VER}_all.udeb
 # get the base_in/exclude stuff in place for bootstrapwrap
@@ -40,19 +41,19 @@ for f in base_include base_exclude ; do
     cp /hd-media/$f /
   else
     INEXCLUDE_URL="/classes/$f"
-    ai_fetch_file ${INEXCLUDE_URL} /$f || log "warning: .../${INEXCLUDE_URL} not found"
+    preseed_fetch ${INEXCLUDE_URL} /$f || log "warning: .../${INEXCLUDE_URL} not found"
   fi
 done
 
 db_progress STEP 1
 # chain onto class specific late_script(s) if any
 for class in $(classes); do
-  db_subst ai/meta/text2 TEXT "Running script for class '$class'"
-  db_progress INFO ai/meta/text2
+  db_subst hands-off/item DESC "Running script for class '$class'"
+  db_progress INFO hands-off/item
 
   CLASS_EARLY_URL="/classes/${class}/early_script"
   cl_a_ss=$(echo ${class}|sed 's/\([^-a-zA-Z0-9]\)/_/g')
-  ai_fetch_file ${CLASS_EARLY_URL} /tmp/early_script-${cl_a_ss} || \
+  preseed_fetch ${CLASS_EARLY_URL} /tmp/early_script-${cl_a_ss} || \
     log "warning: .../${CLASS_EARLY_URL} not found"
 
   if [ -e /tmp/early_script-${cl_a_ss} ] ; then
@@ -63,4 +64,7 @@ for class in $(classes); do
 done
 
 db_progress STOP
+db_unregister hands-off/item
+db_unregister hands-off/title
+
 log "debug: ends successfully"
